name: Test long runner with online status

on:
  workflow_dispatch:

permissions:
  checks: write
  actions: write
  contents: read
env:
  VISIBILITY: public

jobs:
  build-with-logs:
    name: Build with logs and status check - 20 hours
    runs-on: arc-runnerset-base
    timeout-minutes: 2880 # 48 hours
    strategy:
      matrix:
        build-number: [1]
    steps:
      - name: Step 1 - Keep runner alive for 20 hours with logs
        env:
          GH_TOKEN: ${{ secrets.LIST_RUNNERS_TOKEN }}
        run: |
          duration=72000
          end=$((SECONDS+duration))
          echo "Loop will run for $duration seconds."
          while [ $SECONDS -lt $end ]; do
            echo "Waiting for 120 seconds..."
            sleep 120
            echo "Done waiting. Elapsed: $SECONDS seconds."
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/jaylabit/actions/runners
          done